# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CaveSurvey
                                 A QGIS plugin
 Dialog box to input centreline
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-05-21
        copyright            : (C) 2018 by Cave Surveying Group
        email                : aa@wotcc.org.uk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CaveSurvey class from file CaveSurvey.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cave_survey import CaveSurvey
    return CaveSurvey(iface)
